import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";


const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">

      <body data-theme="cupcake"
        className={`${playfair} ${playfair} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
